# Generated by Django 3.2.9 on 2021-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pubdate', models.DateTimeField()),
            ],
        ),
    ]
