# Generated by Django 3.2.9 on 2021-11-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='nick',
            new_name='replyer',
        ),
    ]
