# Generated by Django 3.2.9 on 2021-12-01 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_rename_nick_reply_replyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likey',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
